### ISSUE TITLE
[BUG] Exported datapack uses the wrong folder structure

### ISSUE THREAD

**Issue by pe3ep** [Ayfri/Kore#102]
### Library version

1.15.0-1.21.1

### What module does this bug apply to?

Generation

### What happened?

When exporting a datapack, load and tick JSON files are located under `data/minecraft/tags/functions/load.json` instead of the `data/minecraft/tags/function/load.json`

### How can we reproduce this issue?

1. Create a new project
2. Add a load function inside the datapack
3. Export the datapack (both zip and folder have this issue)
4. Check the folder structure of the exported datapack

### My issue is not duplicated

- [X] This is not a duplicate

**Comment by pe3ep** [comment]
note: the functions in the datapack namespace ARE correct

**Comment by pe3ep** [comment]
![image](https://github.com/user-attachments/assets/430cb82f-8cb0-4867-a4da-a08e0a233d02)

**Comment by Ayfri** [comment]
Oops yes, I forgot to rename the folder for functions on [this line](https://github.com/Ayfri/Kore/blob/master/kore/src/main/kotlin/io/github/ayfri/kore/functions/Function.kt#L179) (and multiple other below).
I will release a hotfix in a few hours and will mention it here as well!

**Comment by pe3ep** [comment]
Thanks! Mojang be making some of the most meaningless changes ever for no reason :D

**Comment by Ayfri** [comment]
@pe3ep The release 1.15.1 which fixes this bug is out! Do not hesitate to create new issues if you find any other bugs or have suggestions for improvements 👍
