### ISSUE TITLE
[BUG] New version seem to broke everything..

### ISSUE THREAD

**Issue by pe3ep** [Ayfri/Kore#103]
### Library version

1.15.1-1.21.1

### What module does this bug apply to?

DSL

### What happened?

![image](https://github.com/user-attachments/assets/8d7977d2-60fa-4cef-92c3-a93628def371)
After updating, datapack function doesn't work. Rolling back on 1.15.0 fixes it
![image](https://github.com/user-attachments/assets/7b94a4b3-7f02-4bb2-a20b-a11ec426e1f8)

### How can we reproduce this issue?

1. Create a new project
2. Add the latest Kore version as dependency
3. Try creating a main datapack function, as in the Kore Template

### Extra information

really odd bug, I hope you can replicate it and its not just on my machine!

### My issue is not duplicated

- [X] This is not a duplicate

**Comment by Ayfri** [comment]
Very weird issue, have you tried restarting Intellij ? Or even reload the cache of Intellij ?

**Comment by Ayfri** [comment]
Haha that's a common issue with JetBrains IDEs.
