### ISSUE TITLE
[FEATURE]  Generate the datapack in a .jar file

### ISSUE THREAD

**Issue by andre-carbajal** [Ayfri/Kore#104]
### What module does this feature apply to?

Generation

### Feature description

Add the option to generate the datapack in a .jar file. The file would contain the same data as the zip file, but some files would have to be added so that the Mod Loaders can detect them

- fabric.mod.json
- quilt.mod.json
- mods.toml

### My issue is not duplicated

- [X] This is not a duplicate

**Comment by Ayfri** [comment]
So that you would be able to use them like mods, like what they do on Modrinth. I'll see how I can do it, if you have big knowledge on this feature, could you list each file to include for each modloader and what variables they need?

**Comment by andre-carbajal** [comment]
- Fabric (**fabric.mod.json**)
    - schemaVersion : 1
    - id
    - version
    - name
    - description
    - license
    - icon
    - authors
    - environment : "*"
    - depends : { "fabric-resource-loader-v0": "*" }

- Quilt (**quilt.mod.json**)
    - schemaVersion : 1
    - quilt_loader
        - group
        - id
        - version
        - metadata
            - name
            - description
            - icon
        - intermediate_mappings : "net.fabricmc:intermediary"
        - depends : [{"id": "quilt_resource_loader","versions": "*","unless": "fabric-resource-loader-v0"}]
        
- Forge (**META-INF/mods.toml**)
    - modLoader = 'lowcodefml'
    - loaderVersion = '[0,)'
    - license
    - showAsResourcePack = false
    - mods
        - modId
        - version
        - displayName
        - description
        - logoFile

- NeoForge (**META-INF/neoforge.mods.toml**)
    - modLoader = 'lowcodefml'
    - loaderVersion = '[0,)'
    - license
    - showAsResourcePack = false
    - mods
        - modId
        - version
        - displayName
        - description
        - logoFile

**Comment by Ayfri** [comment]
Thank you very much! Most of the variables could be reused from the current datapack you're building, I'll see if I can also add a new global variable `CURRENT_MINECRAFT_VERSION` that you can access anywhere, for other ones I'll create a DSL for setting them up.
Example:
```kotlin
dp.generateJar {
    fabric {
        authors = listOf("Me", "You")
        license = File("./my_licence")
    }
    forge {
        ...
    }
}
```
