### ISSUE TITLE
[BUG] Inappropriate argument in setEnchantments item modifier builder

### ISSUE THREAD

**Issue by MushroomMif** [Ayfri/Kore#38]
### Library version

1.0.0

### What module does this bug apply to?

DSL

### What happened?

I tried to use `setEnchantments` item modifier with its builder, but when i tried to add an enchantment to it I noticed that I cant do it. I looked at the source code and seen that in second parameter of function there is a `Map` instead of `MutableMap` and because of that it's impossible to add any enchantments.
![image](https://github.com/Ayfri/Kore/assets/70268320/0eac1470-d704-4151-b303-ef57e79b6045)

### How can we reproduce this issue?

1. Create an item modifier
2. Try to add `setEnchantments` item modifier to it
3. Notice that you cant put any enchantments to the map of enchants

### My issue is not duplicated

- [X] This is not a duplicate

**Comment by Ayfri** [comment]
This bug has been fixed on my computer, you can still create a [SetEnchantments](https://github.com/Ayfri/Kore/blob/master/kore/src/main/kotlin/io/github/ayfri/kore/features/itemmodifiers/functions/SetEnchantments.kt#L10) instance with the values you want as a temporary workaround until the next release.
